package com.church.barnabas.entity;
// Generated 8 May, 2021 6:19:11 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * BusinessTypes generated by hbm2java
 */
@Entity
@Table(name = "business_types", catalog = "churchapp", uniqueConstraints = @UniqueConstraint(columnNames = "business_name"))
public class BusinessTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer businessId;
	private String businessName;
	private Set<Classified> classifieds = new HashSet<Classified>(0);

	public BusinessTypes() {
	}

	public BusinessTypes(String businessName) {
		this.businessName = businessName;
	}

	public BusinessTypes(String businessName, Set<Classified> classifieds) {
		this.businessName = businessName;
		this.classifieds = classifieds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "business_id", unique = true, nullable = false)
	public Integer getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	@Column(name = "business_name", unique = true, nullable = false, length = 155)
	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessTypes")
	@JsonIgnore
	public Set<Classified> getClassifieds() {
		return this.classifieds;
	}

	public void setClassifieds(Set<Classified> classifieds) {
		this.classifieds = classifieds;
	}

}
