package com.church.barnabas.entity;
// Generated 8 May, 2021 6:19:11 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChurchProfile generated by hbm2java
 */
@Entity
@Table(name = "church_profile", catalog = "churchapp")
public class ChurchProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String contactUs;
	private String aboutUs;
	private String onlineReading;
	private String facebook;
	private String school;
	private String website;
	private String bulletIn;
	private String donate;
	private String ministers;
	private String prayerRequest;
	private String youtube;
	private String massTimeIntention;
	private String confessionContact;
	private String confessionEmail;
	private String confessionDetails;
	private String anointingOfTheSick;

	public ChurchProfile() {
	}

	

	


	public ChurchProfile(Integer id, String contactUs, String aboutUs, String onlineReading, String facebook,
			String school, String website, String bulletIn, String donate, String ministers, String prayerRequest,
			String youtube, String massTimeIntention, String confessionContact, String confessionEmail,
			String confessionDetails,String anointingOfTheSick) {
		super();
		this.id = id;
		this.contactUs = contactUs;
		this.aboutUs = aboutUs;
		this.onlineReading = onlineReading;
		this.facebook = facebook;
		this.school = school;
		this.website = website;
		this.bulletIn = bulletIn;
		this.donate = donate;
		this.ministers = ministers;
		this.prayerRequest = prayerRequest;
		this.youtube = youtube;
		this.massTimeIntention = massTimeIntention;
		this.confessionContact = confessionContact;
		this.confessionEmail = confessionEmail;
		this.confessionDetails = confessionDetails;
		this.anointingOfTheSick=anointingOfTheSick;
		
	}











	





	public String getAnointingOfTheSick() {
		return anointingOfTheSick;
	}






	public void setAnointingOfTheSick(String anointingOfTheSick) {
		this.anointingOfTheSick = anointingOfTheSick;
	}






	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "contact_us")
	public String getContactUs() {
		return this.contactUs;
	}

	public void setContactUs(String contactUs) {
		this.contactUs = contactUs;
	}

	@Column(name = "about_us")
	public String getAboutUs() {
		return this.aboutUs;
	}

	public void setAboutUs(String aboutUs) {
		this.aboutUs = aboutUs;
	}

	@Column(name = "online_reading")
	public String getOnlineReading() {
		return this.onlineReading;
	}

	public void setOnlineReading(String onlineReading) {
		this.onlineReading = onlineReading;
	}

	@Column(name = "facebook")
	public String getFacebook() {
		return this.facebook;
	}

	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}

	@Column(name = "school")
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "website")
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "bullet_in")
	public String getBulletIn() {
		return this.bulletIn;
	}

	public void setBulletIn(String bulletIn) {
		this.bulletIn = bulletIn;
	}

	@Column(name = "donate")
	public String getDonate() {
		return this.donate;
	}

	public void setDonate(String donate) {
		this.donate = donate;
	}

	@Column(name = "ministers")
	public String getMinisters() {
		return this.ministers;
	}

	public void setMinisters(String ministers) {
		this.ministers = ministers;
	}

	@Column(name = "prayer_request")
	public String getPrayerRequest() {
		return this.prayerRequest;
	}

	public void setPrayerRequest(String prayerRequest) {
		this.prayerRequest = prayerRequest;
	}

	@Column(name = "youtube")
	public String getYoutube() {
		return this.youtube;
	}

	public void setYoutube(String youtube) {
		this.youtube = youtube;
	}

	@Column(name = "mass_time_intention")
	public String getMassTimeIntention() {
		return this.massTimeIntention;
	}

	public void setMassTimeIntention(String massTimeIntention) {
		this.massTimeIntention = massTimeIntention;
	}


	@Column(name = "confession_contact")

	public String getConfessionContact() {
		return confessionContact;
	}



	public void setConfessionContact(String confessionContact) {
		this.confessionContact = confessionContact;
	}





	@Column(name = "confession_email",length=40)

	public String getConfessionEmail() {
		return confessionEmail;
	}






	public void setConfessionEmail(String confessionEmail) {
		this.confessionEmail = confessionEmail;
	}





	@Column(name = "confession_details",length=10000)

	public String getConfessionDetails() {
		return confessionDetails;
	}






	public void setConfessionDetails(String confessionDetails) {
		this.confessionDetails = confessionDetails;
	}






	
	
	

}
