package com.church.barnabas.entity;
// Generated 8 May, 2021 6:19:11 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Classified generated by hbm2java
 */
@Entity
@Table(name = "classified", catalog = "churchapp")
public class Classified implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private BusinessTypes businessTypes;
	private UserTable userTable;
	private String name;
	private String phoneNumber;
	private String imagename;
	private String businessName;

	

	public Classified() {
	}

	public Classified(BusinessTypes businessTypes, UserTable userTable, String name, String phoneNumber) {
		this.businessTypes = businessTypes;
		this.userTable = userTable;
		this.name = name;
		this.phoneNumber = phoneNumber;
	}

	public Classified(BusinessTypes businessTypes, UserTable userTable, String name, String phoneNumber,
			String imagename) {
		this.businessTypes = businessTypes;
		this.userTable = userTable;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.imagename = imagename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_id", nullable = false)
	@JsonIgnoreProperties(value = {"classified", "hibernateLazyInitializer"})
	public BusinessTypes getBusinessTypes() {
		return this.businessTypes;
	}

	public void setBusinessTypes(BusinessTypes businessTypes) {
		this.businessTypes = businessTypes;
	}
	
	@Column(name="businessName",nullable =false)
	@JsonIgnoreProperties(value = {"classified", "hibernateLazyInitializer"})
	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}
	
	
	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "user_table_id", nullable = false)
	@JsonIgnoreProperties(value = {"classified", "hibernateLazyInitializer"})
	public UserTable getUserTable() {
		return this.userTable;
	}

	public void setUserTable(UserTable userTable) {
		this.userTable = userTable;
	}
	

	@Column(name = "name", nullable = false, length = 180)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone_number", nullable = false, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "imagename")
	public String getImagename() {
		return this.imagename;
	}

	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	

}
