package com.church.barnabas.entity;
// Generated 8 May, 2021 6:19:11 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserTable generated by hbm2java
 */
@Entity
@Table(name = "user_table", catalog = "churchapp", uniqueConstraints = @UniqueConstraint(columnNames = "contact_no"))
public class UserTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String email;
	private String contactNo;
	private String otp;
	private String address;
	private Date otpExpiry;
	private Boolean activeStatus;
	private Set<Classified> classifieds = new HashSet<Classified>(0);
	private Set<UserAnnouncement> userAnnouncements = new HashSet<UserAnnouncement>(0);
	private Set<ScheduleConfession> scheduleConfession = new HashSet<ScheduleConfession>(0);


	public UserTable() {
	}

	public UserTable(String contactNo) {
		this.contactNo = contactNo;
	}





	public UserTable(Integer id, String name, String email, String contactNo, String otp, String address,
			String roleName, Date otpExpiry, Boolean activeStatus, Set<Classified> classifieds,
			Set<UserAnnouncement> userAnnouncements, Set<ScheduleConfession> scheduleConfession) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.contactNo = contactNo;
		this.otp = otp;
		this.address = address;
		this.otpExpiry = otpExpiry;
		this.activeStatus = activeStatus;
		this.classifieds = classifieds;
		this.userAnnouncements = userAnnouncements;
		this.scheduleConfession = scheduleConfession;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_no", unique = true, nullable = false, length = 20)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "otp", length = 8)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Column(name = "address", length = 155)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "otp_expiry", length = 19)
	public Date getOtpExpiry() {
		return this.otpExpiry;
	}

	public void setOtpExpiry(Date otpExpiry) {
		this.otpExpiry = otpExpiry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTable")
	public Set<Classified> getClassifieds() {
		return this.classifieds;
	}

	public void setClassifieds(Set<Classified> classifieds) {
		this.classifieds = classifieds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTable")
	public Set<UserAnnouncement> getUserAnnouncements() {
		return this.userAnnouncements;
	}

	public void setUserAnnouncements(Set<UserAnnouncement> userAnnouncements) {
		this.userAnnouncements = userAnnouncements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contributorId")
	public Set<ScheduleConfession> getScheduleConfession() {
		return scheduleConfession;
	}

	public void setScheduleConfession(Set<ScheduleConfession> scheduleConfession) {
		this.scheduleConfession = scheduleConfession;
	}
	
	@Column(name = "active_status", length = 10)
	public Boolean getActiveStatus() {
		return activeStatus;
	}

	public void setActiveStatus(Boolean activeStatus) {
		this.activeStatus = activeStatus;
	}

	
	
	
	

}
